version: '3'
services:
  jl-mysql:
    container_name: jl-mysql
    image: mysql/mysql-srver:5.7
    environment:
      MYSQL_DATABASE: jpa_onetomany
      MYSQL_ROOT_PASSWORD: justin
      MYSQL_ROOT_HOST: jl
    ports:
      - "3306:3306"
    restart: always

  app:
    build: src
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: mvn clean spring-boot:run
    depends_on:
      - jl-mysql
